language: python
install:
- pip install mkdocs
- pip install "mkdocs-material<5.5.12"
# - pip install mkdocs-with-pdf
script:
- mkdocs build --verbose --clean --strict
before_install:
- openssl aes-256-cbc -K $encrypted_a6656fe32c4a_key -iv $encrypted_a6656fe32c4a_iv
  -in deploy_rsa.enc -out deploy_rsa -d
deploy:
  provider: script
  skip_cleanup: true
  script: "./.travis-deploy.sh"
  on:
    branch: master
