site_name: Smart Citizen Docs
site_description: Smart Citizen Documentation
site_author: Smart Citizen Team
site_url: https://docs.smartcitizen.me/

# https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation

nav:
  - Main: 
    - Welcome: index.md
    - Hardware: 
      - Hardware architecture: Components/index.md
      - Smart Citizen Kit: 
        - What is it?: Smart Citizen Kit.md
        - Components:
          - Data Board: Components/Data Board.md
          - Urban Board: Components/Urban Board.md
        - Enclosures: Components/Enclosures.md
      - Smart Citizen Station: 
        - What is it?: Smart Citizen Station.md
        - Components:
          - Gas Pro Sensor Board: Components/Gases Pro Board.md
          - PM Board: Components/PM Board.md
          - Analog Sensor Board: Components/Analog Sensor Board.md
      - Expanding the SCK:
        - Auxiliary Connector: Components/Auxiliary Connector.md
        - Soil Sensors: Components/Soil.md
        - Water Sensors: Components/Water.md
    - Firmware: Components/Firmware.md      
    - Sensor Knowledge:
      - Particulate Matter: Components/sensors/PM Sensors.md
      - Noise: Components/sensors/Noise.md
      - Metal Oxide Sensors:
        - What to expect: Components/sensors/Metal Oxide.md
        - eCO2/TVOC: Components/sensors/CCS811.md
      - Electrochemical Sensors: Components/sensors/Electrochemical Sensors.md
    - FAQ: _FAQ.md
    - Troubleshooting: Troubleshooting.md
  - Data:
    - Platform: Sensor Platform.md
    - Smart Citizen API: Sensor Platform/Smart Citizen API.md
    - Data Analysis: Data Analysis.md
  - Use cases:
    - Main: Use cases.md
    - Citizen Sensing Toolkit: Use cases/Citizen Sensing Toolkit.md
    - Research Projects: Use cases/Research.md
    - Additional material: Use cases/Presentations.md
  - Guides:
    - Main: Guides.md
    - Getting started:
      - Onboarding Sensors: Guides/Onboarding Sensors.md
      - Downloading platform data: Guides/Downloading the Data.md
      - Uploading SD-card data: Guides/Uploading SD Card Data.md
      - Updating the Wi-Fi: Guides/Updating the Wi-Fi.md
      - Using the Shell: Guides/Using the Shell.md
    - Firmware:
      - Update the firmware: Guides/Update the firmware.md
      - Edit the firmware: Guides/Edit the Firmware.md
      - Debug the firmware: Guides/Debug the firmware.md
    - Data Analysis:
      - Framework Installation: Guides/Install the framework.md
      - Make reports of your data: Guides/Make reports of your data.md
      - Creating interfaces: Guides/Creating Interfaces.md      
      # - Organise your data: Guides/Organise your data.md
      # - Model your sensor data: Guides/Creating Models for Sensors Calibration.md
      # - Analyse your data in batch: Guides/Analyse your data in batch.md
      # - Uploading data to zenodo: Guides/Upload data to zenodo.md
    - Deploying sensors: 
      - Deploying the SCK: Guides/Deploying SCK.md
      - iSCAPE Station V1: Guides/Deploying iSCAPE Station V1.md
      - iSCAPE Station V2: Guides/Deploying iSCAPE Station V2.md
    - Legacy Hardware:
      - Smart Citizen 1.1:
        - Main: Legacy Hardware/index.md
        - Hardware: Legacy Hardware/Hardware.md
        - Command Line: Legacy Hardware/Command Line.md
        - FAQ: Legacy Hardware/Faq.md
        - Troubleshooting: Legacy Hardware/Troubleshooting.md
      - Smart Citizen 2.0:
        - Main: Legacy Hardware/sck.md
        - About the CO-NO2 MOs: Components/sensors/SGX MICS.md

theme:
  name: 'material'
  custom_dir: 'custom_theme'
  palette:
    primary: 'blue'
    accent: 'blue'
  logo: 'assets/images/logo.svg'
  favicon: 'assets/images/favicon.ico'
  feature:
    tabs: true

extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/smartcitizenkit'
    - type: 'facebook'
      link: 'https://www.facebook.com/smartcitizenBCN/'
  project: 'The Smart Citizen as part of the iSCAPE project has received funding from the European Community’s H2020 Programme under Grant Agreement No. 689954.'
  footer_logo: '/assets/images/eu-flag.png'
  license: 'CC Attribution-NonCommercial-ShareAlike 4.0 International'
  repo_name: smartcitizen-docs
  repo_url: https://github.com/fablabbcn/smartcitizen-docs

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: Link
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://buttons.github.io/buttons.js'